name: CI

on: [pull_request, push, release]

jobs:
  prepare:
    name: Prepare
    runs-on:  ubuntu-22.04
    steps:
      - uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16.14.2
  build:
    name: Build
    runs-on: ubuntu-22.04
    needs: prepare
    steps:
      - uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16.14.2
      - run: yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: release
          path: ./dist
      - run: yarn build-google
      - uses: actions/upload-artifact@v2
        with:
          name: release-google
          path: ./dist-google
      - run: yarn build-firefox
      - uses: actions/upload-artifact@v2
        with:
          name: release-firefox
          path: ./dist-firefox
