name: CI

on: [pull_request, push]

jobs:
  prepare:
    name: Prepare
    runs-on:  ubuntu-22.04
    steps:
      - uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16.14.2
  build:
    name: Build
    runs-on: ubuntu-22.04
    needs: prepare
    steps:
      - uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16.14.2
      - run: yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: release.zip
          path: ./dist
  build-google:
    name: Build Google
    runs-on: ubuntu-22.04
    needs: prepare
    steps:
      - uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16.14.2
      - run: yarn build-google
      - uses: actions/upload-artifact@v2
        with:
          name: release-google.zip
          path: ./dist-google
  build-firefox:
    name: Build Firefox
    runs-on: ubuntu-22.04
    needs: prepare
    steps:
      - uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16.14.2
      - run: yarn build-firefox
      - uses: actions/upload-artifact@v2
        with:
          name: release-firefox.zip
          path: ./dist-firefox
