name: CI

on: [pull_request, push]

jobs:
  prepare:
    name: Prepare
    runs-on:  ubuntu-22.04
    steps:
      - uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16.14.2
  build:
    name: Build
    runs-on: ubuntu-22.04
    needs: prepare
    steps:
      - uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16.14.2
      - run: yarn build
      - name: Zip Release
        uses: TheDoctor0/zip-release@0.6.2
        with:
          directory: ./dist
          filename: release.zip
  build-google:
    name: Build Google
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16.14.2
      - run: yarn build-google
      - name: Zip Release
        uses: TheDoctor0/zip-release@0.6.2
        with:
          directory: ./dist-google
          filename: release-google.zip
  build-firefox:
    name: Build Firefox
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16.14.2
      - run: yarn build-firefox
      - name: Zip Release
        uses: TheDoctor0/zip-release@0.6.2
        with:
          directory: ./dist-firefox
          filename: release-firefox.zip
